version: '3'

services:

  solr:
    image: solr
    ports:
     - "8983:8983"

    environment: 
      - SOLR_CORE_CONF_DIR=/Users/kim/SOLR/solr_home/solr-6.6.0/server/solr/wikipages/conf
     
    volumes:
      - data:/Users/kim/SOLR/solr_home/solr-6.6.0/server/solr/wikipages
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - wiki-collection

volumes:
  data: