apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: solr
    spec:
      containers:
      - command:
        - docker-entrypoint.sh
        - solr-precreate
        - wiki-collection
        env:
        - name: SOLR_CORE_CONF_DIR
          value: /Users/kim/SOLR/solr_home/solr-6.6.0/server/solr/wikipages/conf
        image: solr
        name: solr
        ports:
        - containerPort: 8983
        resources: {}
        volumeMounts:
        - mountPath: /Users/kim/SOLR/solr_home/solr-6.6.0/server/solr/wikipages
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
