apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: solr
  annotations:
    acme/certificate: wiki-search.di-dev.gcp0.bwcom.net
    acme/secretName: wiki-search-certificate
spec:
  ports:
    - port: 8983
      targetPort: 8983
  selector:
    app: solr

